version: "3.8"
services:
  rag_app:
    build: .
    volumes:
      - ./rag_data:/app/data
    environment:
      QDRANT_HOST: qdrant_instance
      QDRANT_PORT: 6333
      OLLAMA_BASE_URL: http://host.docker.internal:11434
    depends_on:
      - qdrant_instance
    ports:
      - "8000:8000"

  qdrant_instance:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./test_data/qdrant:/qdrant/storage # Mount test data for testing

volumes:
  rag_data:
